update main.yml --> with error
for testing

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -6,5 +6,11 @@ jobs:
     steps:
       - uses: actions/checkout@v2
         
-      - name: run a one-line script
-        run: echo "Hello World!!"
+      - name: Greeting
+        run: echo "Hello, world!"
+
+      - name: Simulate an error
+        run: echo "About to fail" ; exit 1
+
+      - name: Another greeting
+        run: echo "Hello, world!"
